version: '3'
services:
  extract:
    build:
      context: .
      dockerfile: Dockerfile_extract
    ports:
      - 8000:8000
    volumes:
      - shared_data:/app

  load:
    build:
      context: .
      dockerfile: Dockerfile_load
    ports:
      - 8050:8050
    depends_on:
      - transform
    volumes:
      - shared_data:/app
    restart: always

  transform:
    build:
      context: .
      dockerfile: Dockerfile_transform
    depends_on:
      - extract
    volumes:
      - shared_data:/app

volumes:
  shared_data: